import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>聖言十步App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>聖言十步App已全面升級</h1>

        <h2>
          請訪問新的網址
          <a href="https://www.10step.net/">https://www.10step.net/</a>
        </h2>
      </main>
    </div>
  );
}
